#!/usr/bin/env python3
"""Scaffold the nextjs-enhancement/ artifact tree. DRY-RUN BY DEFAULT.

Creates only the directory skeleton and plants README.md as the shared format
authority. It never writes finding or task content — that is the orchestrator's
and the agents' job (a scaffolder that invents content produces stubs nobody
trusts).

Usage:
    scaffold-plan.py <repo-root>                          # dry run: print the plan
    scaffold-plan.py <repo-root> --apply                  # create dirs + README
    scaffold-plan.py <repo-root> --apply --domains a,b,c  # only these findings dirs
    scaffold-plan.py <repo-root> --apply --readme <path>  # source the README body
"""

from __future__ import annotations

import argparse
import shutil
import sys
from datetime import date
from pathlib import Path

ROOT_DIR = "nextjs-enhancement"

ALL_DOMAINS = [
    "rendering-strategy-caching",
    "image-optimization",
    "font-script-optimization",
    "bundle-code-splitting",
    "navigation-prefetching",
    "page-transitions-view-transitions",
    "micro-interactions-react19-fluidity",
    "dark-light-theme-switching",
    "instant-i18n-locale-switching",
    "data-fetching-patterns",
    "seo-metadata",
    "build-performance-turbopack",
    "vercel-platform-deployment",
    "measurement-regression-guardrails",
]

FALLBACK_README = """# nextjs-enhancement

Generated by the `optimize-nextjs-fluidity` skill.

## Layout

```
nextjs-enhancement/
├── README.md                  this file — the format authority
├── 00-recon.md                repo profile: versions, capability probe, inventory
├── 01-applicability.md        per-domain verdicts; what was deliberately withheld
├── findings/<domain>/NN-*.md  audit evidence, one issue per file
├── tasks/00-INDEX.md          the plan: order, dependencies, waves, status
├── tasks/NN-<verb-object>.md  one file per task — the executable unit
└── 02-completion-report.md    what actually happened
```

## Conventions

**Status** — `pending` · `in-progress` · `done` · `blocked` · `blocked-needs-human` ·
`wontfix`. Nothing else parses.

**Severity** — `critical` (removed surface in use, build/runtime error, user-visible
breakage) · `major` (P0 practice absent/misconfigured for this archetype) · `minor`
(deprecated-but-working, unadopted stable opt-in) · `informational` (deliberate
divergence worth noting; never a task alone).

**Reversibility** — `fully-reversible` · `component-level-revert` ·
`migration-required` (one-way door; never auto-applied).

**Ordinals encode dependencies**, not discovery order.

**Evidence is literal** — `file:line` plus exact matched text, with the command that
found it.

## Guarantees

- Nothing recommended that the installed Next.js does not support (probed against
  `node_modules`, not inferred from a version string).
- No one-way door executed automatically.
- Every applied task verified by running its own check; failures reverted and reported.
- Nothing pushed, merged, or deployed; dependencies and lockfiles untouched.
- Practices the repo already follows correctly were not re-proposed.

## Re-running

A later run creates a new dated folder rather than overwriting this one.

```bash
python3 scripts/status-report.py nextjs-enhancement/
```
"""


def plan_paths(base: Path, domains: list[str]) -> list[Path]:
    return [base, base / "findings", *[base / "findings" / d for d in domains], base / "tasks"]


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold nextjs-enhancement/ (dry-run by default).")
    ap.add_argument("repo_root")
    ap.add_argument("--apply", action="store_true", help="actually create dirs and README")
    ap.add_argument("--domains", help="comma-separated applicable domains (default: all 14)")
    ap.add_argument("--readme", help="path to references/artifact/artifact-readme.md to source the body from")
    ap.add_argument("--force", action="store_true", help="allow writing into an existing non-empty tree")
    args = ap.parse_args()

    root = Path(args.repo_root).expanduser().resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 2

    domains = [d.strip() for d in args.domains.split(",") if d.strip()] if args.domains else ALL_DOMAINS
    unknown = [d for d in domains if d not in ALL_DOMAINS]
    if unknown:
        print(f"error: unknown domain(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    base = root / ROOT_DIR
    paths = plan_paths(base, domains)

    if not args.apply:
        print(f"DRY RUN — nothing written. Target: {base}\n")
        print("Would create:")
        for p in paths:
            print(f"  {p.relative_to(root)}/")
        print(f"  {(base / 'README.md').relative_to(root)}")
        print(f"\n{len(domains)} findings dirs. Re-run with --apply to create.")
        if base.exists():
            print(f"\nNOTE: {base.relative_to(root)} already exists — use --force to write into it.")
        return 0

    if base.exists() and any(base.iterdir()) and not args.force:
        print(
            f"error: {base} already exists and is not empty.\n"
            "A previous run's artifact must not be silently overwritten — move it aside, "
            "use a dated folder, or pass --force.",
            file=sys.stderr,
        )
        return 3

    for p in paths:
        p.mkdir(parents=True, exist_ok=True)

    readme = base / "README.md"
    body = None
    if args.readme:
        src = Path(args.readme).expanduser().resolve()
        if not src.is_file():
            print(f"error: --readme not found: {src}", file=sys.stderr)
            return 2
        text = src.read_text(encoding="utf-8")
        # the reference file wraps the plantable body in the first fenced block
        if "```markdown" in text:
            body = text.split("```markdown", 1)[1].rsplit("```", 1)[0].lstrip("\n")
    readme.write_text(body or FALLBACK_README, encoding="utf-8")

    print(f"Created {base.relative_to(root)}/ with {len(domains)} findings dirs.")
    print(f"Planted {readme.relative_to(root)} ({'from ' + args.readme if body else 'built-in fallback'}).")
    print("\nNext: write 00-recon.md and 01-applicability.md, then dispatch the audit wave.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
